from PIL import Image, ImageDraw, ImageFont


def create_spotify_infographic(stats_data: dict) -> Image.Image:
    """
    Generate an infographic from Spotify stats data
    Returns: PIL Image object
    """
    # Canvas settings
    width, height = 800, 600
    bg_color = (18, 18, 18)  # Spotify dark theme
    accent_color = (30, 215, 96)  # Spotify green
    text_color = (255, 255, 255)

    # Create image
    img = Image.new("RGB", (width, height), bg_color)
    draw = ImageDraw.Draw(img)

    # Try to load fonts (fallback to default if not available)
    try:
        title_font = ImageFont.truetype(
            "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 36
        )
        header_font = ImageFont.truetype(
            "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 24
        )
        text_font = ImageFont.truetype(
            "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 18
        )
    except:
        title_font = ImageFont.load_default()
        header_font = ImageFont.load_default()
        text_font = ImageFont.load_default()

    # Title
    draw.text((20, 20), "My Spotify Stats", fill=accent_color, font=title_font)

    y_offset = 80

    # Top Artists Section
    draw.text(
        (20, y_offset), "🎤 Top Artists (Short Term)", fill=text_color, font=header_font
    )
    y_offset += 40

    top_artists = stats_data.get("top_artists", {}).get("short_term", {})
    for i, (idx, artist) in enumerate(list(top_artists.items())[:5]):
        artist_name = artist.get("name", "Unknown")
        genre = artist.get("genre", "Unknown")

        # Truncate long names
        if len(artist_name) > 30:
            artist_name = artist_name[:27] + "..."

        draw.text(
            (40, y_offset), f"{i+1}. {artist_name}", fill=text_color, font=text_font
        )
        draw.text((450, y_offset), f"({genre})", fill=(150, 150, 150), font=text_font)
        y_offset += 30

    y_offset += 20

    # Top Songs Section
    draw.text(
        (20, y_offset), "🎵 Top Songs (Short Term)", fill=text_color, font=header_font
    )
    y_offset += 40

    top_songs = stats_data.get("top_songs", {}).get("short_term", {})
    for i, (idx, song) in enumerate(list(top_songs.items())[:5]):
        song_name = song.get("name", "Unknown")
        artist_name = song.get("artist", "Unknown")

        if len(song_name) > 25:
            song_name = song_name[:22] + "..."
        if len(artist_name) > 20:
            artist_name = artist_name[:17] + "..."

        draw.text(
            (40, y_offset), f"{i+1}. {song_name}", fill=text_color, font=text_font
        )
        draw.text(
            (450, y_offset), f"by {artist_name}", fill=(150, 150, 150), font=text_font
        )
        y_offset += 30

    # Footer
    draw.text(
        (20, height - 40),
        "Generated by SpotifyStats API",
        fill=(100, 100, 100),
        font=text_font,
    )

    return img
